[package]
name = "pb-ebnf-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
pb-ebnf-core = { path = "../core/" }
proc-macro2 = { version = "1.0.86", features = ["span-locations"] }
quote = "1.0.36"
syn = { version = "2.0.72", features = ["parsing"] }
